config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :recipes, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all 
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to root_path, notice: 'Receita cadastrada com sucesso.'
    else 
      render 'new', notice: 'Não foi possível cadastrar a receita'
    end

  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :ingredients, :time_to_prepare, :recipe_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2>Cookbook</h2>

<%= link_to 'Cadastrar Receita', new_recipe_path %>

<% if @recipes.any? %>
  <% @recipes.each do |r|%>
    <%= link_to r.name, recipe_path(r) %> 
  <% end %>
<% else %>
  <p>Não existem receitas cadastradas</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= notice  %>
    <%= yield %>
  </body>
</html>

app/views/recipes/new.html.erb
<h2>Cadastrar Receita</h2>

<%= form_with(model: @recipe) do |f| %>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.label :time_to_prepare, 'Tempo de preparo' %>
  <%= f.text_field :time_to_prepare  %>
  <%= f.label :recipe_type, 'Tipo de receita' %>
  <%= f.text_field :recipe_type %>
  <%= f.label :ingredients, 'Ingredientes' %>
  <%= f.text_area :ingredients %>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/recipes/show.html.erb
<%= link_to "Voltar", root_path %>

<h1>Reiceita: <%= @recipe.name%></h1>

<ul>
  <li>Receita: <%= @recipe.name %></li>
  <li>Tempo de preparo: <%= @recipe.time_to_prepare %></li>
  <li>Ingredientes: <%= @recipe.ingredients %></li>
  <li>Tipo de receita: <%= @recipe.recipe_type %> </li>
</ul>